name: Release

on:
  push:
    branches:
      - release

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: [self-hosted, front]
    name: Build frontend and deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: rysnc -a ./dist/mempool/ ngwa1:/var/www/mempool/
